# For local development and tryouts.
version: "3"

services:
  ghost:
    image: ghcr.io/sredevopsdev/ghost-on-kubernetes:main
    command: ["node", "current/index.js"]
    platform: linux/amd64
    container_name: ghost
    volumes:
      - ./content:/var/lib/ghost/content
      - ./ghost-local2.db:/var/lib/ghost/content/data/ghost-local.db
    environment:
      NODE_ENV: development
      database__client: sqlite3
      database__connection__filename: content/data/ghost-local.db
    ports:
      - 2368:2368
